---
title: "Homework 4 - Lightning Strike Analysis"
author: Jack Bienvenue
date: 20 September 2025
format: pdf
header-includes:
  - \usepackage{tcolorbox}
  - \tcbset{colback=red!10!white, colframe=red!80!black, boxrule=0.5pt, arc=3pt, left=6pt, right=6pt, top=6pt, bottom=6pt}
  - \usepackage{xcolor}
  - \newcommand{\red}[1]{\textcolor{red}{#1}}
---

# Task 1: Replicating Lightning Strike Point Pattern Map

```{r, echo=FALSE}
#----------------PRELIMINARIES-------------------#
# Package import
invisible(suppressWarnings(suppressMessages(lapply(c("sp", "spdep", "ggplot2",
                                                     "gstat", "sf", "dplyr", 
                                                     "tidyr", "RColorBrewer",
                                                     "ncdf4", "maps",
                                                     "mapdata",
                                                     "spatstat", "raster"), 
                                            require, character.only = TRUE))))
options(warn = -1)
# Data import

## Provide 

in_dir  <- "../../data/GOES/2023/06/14"

# --- 1) Collect & filter lightning coordinates from all NetCDF files --------
nc_files <- list.files(in_dir, full.names = TRUE)

LONLAT <- do.call(
  rbind,
  lapply(nc_files, function(f) {
    nc <- nc_open(f)
    on.exit(nc_close(nc), add = TRUE)
    
    # Read variables
    lon <- ncvar_get(nc, "flash_lon")
    lat <- ncvar_get(nc, "flash_lat")
    eng <- ncvar_get(nc, "flash_energy")  # Joules
    
    # Keep energetic flashes in a reasonable CONUS-ish box
    keep <- which(eng > 1e-11 & lat > 20 & lon > -100)  
    if (length(keep) == 0) return(NULL)
    
    cbind(LON = lon[keep], LAT = lat[keep])
  })
)
strikes_df <- as.data.frame(LONLAT)
```

```{r, echo=FALSE}
strikes_sf <- st_as_sf(strikes_df, coords = c("LON", "LAT"), crs = 4326)
us_states <- map_data("state")
ggplot() +
  geom_polygon(data = us_states, aes(x = long, y = lat, group = group),
               fill = NA, color = "black", size = 0.3) +
  geom_point(data = strikes_df, aes(x = LON, y = LAT),
             color = "red", size = 1, alpha = 0.5) +
  coord_fixed(ratio = 4/4.75, xlim = c(-100, -77.5), ylim = c(20, 40), expand = FALSE) +
  theme_minimal(base_size = 12) +
  theme(
    panel.grid = element_blank(), 
    panel.border = element_rect(   
      colour = "black", fill = NA, size = 1
    ),
    axis.title = element_text(),
    axis.text = element_text(), 
    plot.title = element_text(hjust = 0.5)  
  ) +
  labs(
    title = "Locations of Lightning Strikes: June 14, 2023",
    x = "Longitude", y = "Latitude"
  )
```

```{=tex}
\centering{\red{Question: Does the pattern look completely random, clustered, or regular?}}

\begin{tcolorbox}
There appears to be a number of clusters in the dataset, particularly in the Texarkana region, eastern Georgia, and between Orlando, FL and Miami, FL. There is another cluster offshore, southwest of Florida's Everglades. There also appears to be a longitudinal swath of the Southern United States with a density of lightning strikes, likely suggesting the movement of a storm. No-lightning ``cold spots" occupy much of the area that is outside of these Southern states. 

We also notice sometihng that may be a data recording artifact. Around 25 degrees of latitude, there is a linear path of lightning strikes. Weather data collection is not a perfect science despite its amazing capabilities!
\end{tcolorbox}
```

---

# Task 2: Replicating G-function Plot for Lightning

```{r, echo=FALSE}
# To prepare for nearest-neighbor methods, it is essential to project our 
# data, because distances must be meaningful. 

## Reproject to US UTM Zone 16 (centered longitudinally in ROI) 
strikes_proj <- st_transform(strikes_sf, 32616)

## Extract projected coordinates
coords <- st_coordinates(strikes_proj)

## Set up some crucial variables
N       <- nrow(strikes_proj)
### Get bounding box window
W_box <- owin(xrange = range(coords[,1]),
          yrange = range(coords[,2]))
area_W  <- area.owin(W_box)
lambda  <- N / area_W       # points per unit²
unit_m  <- 1 # UTM units are 1m
lambda_m2 <- lambda / (unit_m^2)

## Make the point pattern
pp <- ppp(x=coords[,1], y=coords[,2], window=W_box)

## For each lightning strike, find its nearest neighbour
nn_id  <- nnwhich(pp)        # index of nearest neighbour for each tree
nn_dist <- nndist(pp)/1000        # nearest neighbour distances (km scale)

# Plot ECDF
plot(ecdf(nn_dist),
     do.points = FALSE, verticals = TRUE,
     xlab = "r (km)", ylab = "G(r)",
     main = "G-function(Nearest-Neighbour ECDF) — Lightning Strikes",
     ylim = c(0,1),
     xlim = c(0,250))
r <- seq(0, max(nn_dist)*1.05, length.out = 400)
lines(r, 1 - exp(-pi * lambda * (r*1000)^2), lty = 2) # CSR baseline, r in m 
legend("bottomright",
       c("observed", "CSR benchmark"),
       lty = c(1,2,3), bty = "n")

```

```{=tex}
\centering{\red{Question: Does the pattern look completely random, clustered, or regular?}}

\begin{tcolorbox}
It appears that for the bulk of the ECDF, the nearest neighbors are closer than they would be for randomly distributed data within the region of interest window. We can tell because the empirical distribution of true lightning strike points lays to the left of the empirical distribution of randomly located points, corresponding to lower nearest neighbor distances for our data. This implies that our may be clustered to an extent we would not expect from randomly distributed points. 
\end{tcolorbox}
```

---

# Task 3: Gaussian Kernel Density Estimate of Lightning Strikes

```{r, echo=FALSE}
# Build KDE framework
bw_dig <- bw.diggle(pp)
bw_ppl <- bw.ppl(pp)
sigma_m <- 34500 #m

D_sel <- density.ppp(pp, sigma = sigma_m, kernel = "gaussian",
                     edge = TRUE, at = "pixels", dimyx = 256)

# Build plot

## Project us states to utm to be compatible w/ KDE for mapping
us_states <- map_data("state") # keeps long/lat
us_states_sf <- st_as_sf(us_states, coords = c("long", "lat"), crs = 4326, remove = FALSE)
us_states_utm <- st_transform(us_states_sf, 32616)

## Convert KDE to raster for ggplot
D_raster <- raster(D_sel)
D_df <- as.data.frame(rasterToPoints(D_raster))
colnames(D_df) <- c("x", "y", "density")
D_df$dens_km2 <- D_df$density * 1e6

## Complete plot
ggplot() +
  geom_sf(data = us_states_utm, fill = NA, color = "black", size = 0.3) +
  geom_raster(data = D_df, aes(x = x, y = y, fill = dens_km2), alpha = 0.9) +
  scale_fill_gradientn(
    colors = c("navy", "blue3", "red3", "red", "yellow"),
    guide = guide_colorbar(
      barheight = unit(8, "cm"),  # taller legend
      barwidth = unit(0.5, "cm")
    )) +
  coord_sf(xlim = range(coords[,1]), ylim = range(coords[,2])) +
  theme_minimal(base_size = 12) +
  theme(
    panel.grid = element_blank(),
    panel.border = element_rect(colour = "black", fill = NA, size = 1),
    axis.title = element_text(),
    axis.text = element_text(),
    plot.title = element_text(hjust = 0.5)
  ) +
  labs(
    title = "Gaussian KDE (σ = 34.5 km, 5x median NN dist)",
    x = NULL, y = NULL,
    fill = NULL  # remove legend label
  )
```

```{=tex}
\centering{\red{Question: Are lightning strikes equally likely everywhere, or do hotspots exist?}}

\begin{tcolorbox}
Since we are working with lightning strike data from a singular day, we will only generalize for that day. Lightning strikes do not appear to be equally likely everywhere. We began to suspect this earlier on in our analysis, and we observe this again in this task. We observe hotspots for lightning strike events.

Our kernel density estimate identifies a number of hotspots which appear to have a higher probability of lightning strikes on this day. These include West Palm Beach, FL, Montgomery, AL, Texarkana, TX (and AR), Eastern Georgia, and some outlying areas southwest of Florida's Everglades. Other areas which previous had some density of lightning strikes do not appear as hotspots in this map with the given parameters.

One caveat to this conclusion could be that we do not know whether the detection rate of lightning is equal across our region of interest. If there was reason to believe that our hotspots (and only our hotspots) had more sensitivity to lightning detection, our claims of hotspot detection may not be valid.
\end{tcolorbox}
```